packages:
  - apps/*
  - packages/*
  - tools/*
catalog:
  '@auth/drizzle-adapter': ^1.7.4
  '@eslint/js': ^9.21.0
  '@hono/node-server': ^1.13.8
  '@hono/trpc-server': ^0.3.4
  '@radix-ui/react-avatar': ^1.1.3
  '@radix-ui/react-dialog': ^1.1.6
  '@radix-ui/react-dropdown-menu': ^2.1.6
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.2
  '@radix-ui/react-slot': ^1.1.2
  '@radix-ui/react-toast': ^1.2.6
  '@tailwindcss/vite': 4.0.7
  '@tanstack/react-form': ^0.43.2
  '@tanstack/react-query': 5.66.9
  '@tanstack/react-router': ^1.109.2
  '@tanstack/router-devtools': ^1.109.2
  '@tanstack/router-plugin': ^1.109.2
  '@trpc/client': 11.0.0-rc.802
  '@trpc/server': 11.0.0-rc.802
  '@trpc/tanstack-react-query': 11.0.0-rc.802
  '@types/eslint-config-prettier': ^6.11.3
  '@types/node': ^22.13.5
  '@types/pg': ^8.11.11
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  '@vitejs/plugin-react-swc': ^3.8.0
  better-auth: ^1.1.19
  class-variance-authority: ^0.7.1
  dotenv-cli: ^8.0.0
  drizzle-kit: ^0.30.4
  drizzle-orm: ^0.39.3
  drizzle-valibot: ^0.4.0
  eslint: ^9.21.0
  eslint-config-prettier: ^10.0.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-turbo: ^2.4.2
  globals: ^16.0.0
  hono: ^4.7.2
  next-themes: ^0.4.4
  pg: ^8.13.3
  prettier: ^3.5.1
  radix-ui: ^1.1.3
  react: ^19.0.0
  react-dom: ^19.0.0
  sonner: ^2.0.1
  superjson: ^2.2.2
  tailwind-merge: ^3.0.1
  tailwindcss: ^4.0.8
  tailwindcss-animate: ^1.0.7
  tsx: ^4.19.3
  turbo: ^2.4.2
  typescript: ^5.7.3
  typescript-eslint: ^8.24.1
  url-join: ^5.0.0
  valibot: 1.0.0-rc.1
  vite: ^6.1.1
