packages:
  - apps/*
  - packages/*
  - tools/*
catalog:
  '@eslint/js': ^9.23.0
  '@hono/node-server': ^1.14.0
  '@hono/trpc-server': ^0.3.4
  '@next/eslint-plugin-next': ^15.2.4
  '@radix-ui/react-avatar': ^1.1.3
  '@radix-ui/react-dialog': ^1.1.6
  '@radix-ui/react-dropdown-menu': ^2.1.6
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.2
  '@radix-ui/react-slot': ^1.1.2
  '@radix-ui/react-toast': ^1.2.6
  '@radix-ui/react-tooltip': ^1.1.8
  '@tailwindcss/vite': ^4.0.17
  '@tanstack/react-form': ^1.2.3
  '@tanstack/react-query': ^5.71.1
  '@tanstack/react-router': ^1.114.29
  '@tanstack/router-devtools': ^1.114.31
  '@tanstack/router-plugin': ^1.114.31
  '@trpc/client': ^11.0.1
  '@trpc/server': ^11.0.1
  '@trpc/tanstack-react-query': ^11.0.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/node': ^22.13.14
  '@types/pg': ^8.11.11
  '@types/react': ^19.0.12
  '@types/react-dom': ^19.0.4
  '@vitejs/plugin-react-swc': ^3.8.1
  better-auth: ^1.2.5
  class-variance-authority: ^0.7.1
  dotenv-cli: ^8.0.0
  drizzle-kit: ^0.30.6
  drizzle-orm: ^0.41.0
  drizzle-valibot: ^0.4.1
  eslint: ^9.23.0
  eslint-config-prettier: ^10.1.1
  eslint-config-turbo: ^2.4.4
  eslint-plugin-import: ^2.31.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.4.4
  globals: ^16.0.0
  hono: ^4.7.5
  next-themes: ^0.4.6
  pg: ^8.14.1
  prettier: ^3.5.3
  radix-ui: ^1.1.3
  react: ^19.1.0
  react-dom: ^19.1.0
  shx: ^0.4.0
  sonner: ^2.0.2
  superjson: ^2.2.2
  tailwind-merge: ^3.1.0
  tailwindcss: ^4.0.17
  tailwindcss-animate: ^1.0.7
  tsup: ^8.4.0
  tsx: ^4.19.3
  turbo: ^2.4.4
  typescript: ^5.8.2
  typescript-eslint: ^8.29.0
  url-join: ^5.0.0
  valibot: ^1.0.0
  vite: ^6.2.4
